# Generated by Django 3.1.1 on 2022-12-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BgAudit',
            fields=[
                ('auditid', models.BigAutoField(db_column='AuditId', primary_key=True, serialize=False)),
                ('bgid', models.BigIntegerField(db_column='BGId')),
                ('businessterm', models.CharField(db_column='BusinessTerm', max_length=30)),
                ('definition', models.CharField(db_column='Definition', max_length=100)),
                ('dataattribute', models.CharField(db_column='DataAttribute', max_length=30)),
                ('system', models.CharField(db_column='System', max_length=30)),
                ('dataclassification', models.CharField(db_column='DataClassification', max_length=30)),
                ('datadomain', models.CharField(db_column='DataDomain', max_length=30)),
                ('lineofbusiness', models.CharField(db_column='LineOfBusiness', max_length=30)),
                ('status', models.CharField(db_column='Status', max_length=30)),
                ('createdby', models.CharField(db_column='CreatedBy', max_length=30)),
                ('create_timestamp', models.DateTimeField(db_column='Create_Timestamp')),
                ('update_timestamp', models.DateTimeField(db_column='Update_Timestamp')),
                ('auditaction', models.CharField(db_column='AuditAction', max_length=1)),
                ('auditdate', models.DateTimeField(db_column='AuditDate')),
                ('audituser', models.CharField(db_column='AuditUser', max_length=50)),
                ('auditapp', models.CharField(db_column='AuditApp', max_length=128)),
            ],
            options={
                'db_table': 'BG_AUDIT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BgMain',
            fields=[
                ('bgid', models.BigAutoField(db_column='BGId', primary_key=True, serialize=False)),
                ('businessterm', models.CharField(db_column='BusinessTerm', max_length=30)),
                ('definition', models.CharField(db_column='Definition', max_length=100)),
                ('dataattribute', models.CharField(db_column='DataAttribute', max_length=30)),
                ('system', models.CharField(db_column='System', max_length=30)),
                ('dataclassification', models.CharField(db_column='DataClassification', max_length=30)),
                ('datadomain', models.CharField(db_column='DataDomain', max_length=30)),
                ('lineofbusiness', models.CharField(db_column='LineOfBusiness', max_length=30)),
                ('status', models.CharField(db_column='Status', max_length=30)),
                ('createdby', models.CharField(db_column='CreatedBy', max_length=30)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, db_column='Create_Timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now_add=True, db_column='Update_Timestamp')),
            ],
            options={
                'db_table': 'BG_MAIN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessFunction',
            fields=[
                ('businessfuncid', models.BigAutoField(db_column='BusinessFuncId', primary_key=True, serialize=False)),
                ('organization', models.CharField(db_column='Organization', max_length=8000)),
                ('businessfunc', models.CharField(db_column='BusinessFunc', max_length=30)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=100, null=True)),
            ],
            options={
                'db_table': 'BUSINESS_FUNCTION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roleid', models.BigAutoField(db_column='RoleId', primary_key=True, serialize=False)),
                ('organization', models.TextField(db_column='Organization')),
                ('role', models.CharField(db_column='Role', max_length=50)),
                ('role_description', models.TextField(blank=True, db_column='Role_Description', null=True)),
            ],
            options={
                'db_table': 'ROLES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RopaAudit',
            fields=[
                ('auditid', models.BigAutoField(db_column='AuditId', primary_key=True, serialize=False)),
                ('ropamainid', models.BigIntegerField(db_column='ROPAMAINId')),
                ('ropaid', models.BigIntegerField(db_column='ROPAId')),
                ('bgid', models.BigIntegerField(db_column='BGId')),
                ('ropaty', models.CharField(db_column='ROPATy', max_length=30)),
                ('businessfunc', models.CharField(db_column='BusinessFunc', max_length=50)),
                ('processingactivityname', models.TextField(blank=True, db_column='ProcessingActivityName', null=True)),
                ('processingactivitydesc', models.TextField(blank=True, db_column='ProcessingActivityDesc', null=True)),
                ('categoriesdatasubjects', models.CharField(db_column='CategoriesDataSubjects', max_length=50)),
                ('categoriespersonaldata', models.CharField(db_column='CategoriesPersonalData', max_length=50)),
                ('controllername', models.CharField(db_column='ControllerName', max_length=50)),
                ('categoriesofrecepients', models.CharField(db_column='CategoriesofRecepients', max_length=50)),
                ('lawfulbasisofprocessing', models.CharField(db_column='LawfulBasisOfProcessing', max_length=50)),
                ('retentionschedule', models.CharField(db_column='RetentionSchedule', max_length=50)),
                ('dataprocessor', models.TextField(blank=True, db_column='DataProcessor', null=True)),
                ('linkcontractprocessor', models.TextField(db_column='LinkContractProcessor')),
                ('countriesdetailstransferred', models.CharField(db_column='CountriesDetailsTransferred', max_length=50)),
                ('safeguardsexternaltransfers', models.CharField(db_column='SafeguardsExternalTransfers', max_length=50)),
                ('securitymeasures_desc', models.TextField(db_column='SecurityMeasures_Desc')),
                ('linkscontracts', models.TextField(db_column='LinksContracts')),
                ('status', models.CharField(db_column='Status', max_length=30)),
                ('create_timestamp', models.DateTimeField(db_column='Create_Timestamp')),
                ('update_timestamp', models.DateTimeField(db_column='Update_Timestamp')),
                ('auditaction', models.CharField(db_column='AuditAction', max_length=1)),
                ('auditdate', models.DateTimeField(db_column='AuditDate')),
                ('audituser', models.CharField(db_column='AuditUser', max_length=50)),
                ('auditapp', models.CharField(db_column='AuditApp', max_length=128)),
            ],
            options={
                'db_table': 'ROPA_AUDIT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RopaMain',
            fields=[
                ('ropamainid', models.BigAutoField(db_column='ROPAMAINId', primary_key=True, serialize=False)),
                ('ropaty', models.CharField(db_column='ROPATy', max_length=30)),
                ('businessfunc', models.CharField(db_column='BusinessFunc', max_length=50)),
                ('processingactivityname', models.TextField(blank=True, db_column='ProcessingActivityName', null=True)),
                ('processingactivitydesc', models.TextField(blank=True, db_column='ProcessingActivityDesc', null=True)),
                ('categoriesdatasubjects', models.CharField(db_column='CategoriesDataSubjects', max_length=50)),
                ('categoriespersonaldata', models.CharField(db_column='CategoriesPersonalData', max_length=50)),
                ('controllername', models.CharField(db_column='ControllerName', max_length=50)),
                ('categoriesofrecepients', models.CharField(db_column='CategoriesofRecepients', max_length=50)),
                ('lawfulbasisofprocessing', models.CharField(db_column='LawfulBasisOfProcessing', max_length=50)),
                ('retentionschedule', models.CharField(db_column='RetentionSchedule', max_length=50)),
                ('dataprocessor', models.TextField(blank=True, db_column='DataProcessor', null=True)),
                ('linkcontractprocessor', models.TextField(db_column='LinkContractProcessor')),
                ('countriesdetailstransferred', models.CharField(db_column='CountriesDetailsTransferred', max_length=50)),
                ('safeguardsexternaltransfers', models.CharField(db_column='SafeguardsExternalTransfers', max_length=50)),
                ('securitymeasures_desc', models.TextField(db_column='SecurityMeasures_Desc')),
                ('linkscontracts', models.TextField(db_column='LinksContracts')),
                ('status', models.CharField(db_column='Status', max_length=30)),
                ('create_timestamp', models.DateTimeField(db_column='Create_Timestamp')),
                ('update_timestamp', models.DateTimeField(db_column='Update_Timestamp')),
            ],
            options={
                'db_table': 'ROPA_MAIN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RopaType',
            fields=[
                ('ropaid', models.BigAutoField(db_column='ROPAId', primary_key=True, serialize=False)),
                ('ropaty', models.CharField(db_column='ROPATy', max_length=30, null=True)),
                ('name', models.TextField(db_column='Name')),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('country_code', models.IntegerField(blank=True, db_column='Country_Code', null=True)),
                ('telephone', models.IntegerField(blank=True, db_column='Telephone', null=True)),
                ('dpo_name', models.TextField(blank=True, db_column='DPO_Name', null=True)),
                ('dpo_address', models.TextField(blank=True, db_column='DPO_Address', null=True)),
                ('dpo_email', models.CharField(blank=True, db_column='DPO_Email', max_length=100, null=True)),
                ('dpo_country_code', models.IntegerField(blank=True, db_column='DPO_Country_Code', null=True)),
                ('dpo_phone', models.IntegerField(blank=True, db_column='DPO_Phone', null=True)),
                ('rep_name', models.TextField(blank=True, db_column='Rep_Name', null=True)),
                ('rep_address', models.TextField(blank=True, db_column='Rep_Address', null=True)),
                ('rep_email', models.CharField(blank=True, db_column='Rep_Email', max_length=100, null=True)),
                ('rep_country_code', models.IntegerField(blank=True, db_column='Rep_Country_Code', null=True)),
                ('rep_phone', models.IntegerField(blank=True, db_column='Rep_Phone', null=True)),
            ],
            options={
                'db_table': 'ROPA_TYPE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('userid', models.BigAutoField(db_column='UserId', primary_key=True, serialize=False)),
                ('organization', models.CharField(db_column='Organization', max_length=8000)),
                ('businessfunc', models.CharField(blank=True, db_column='BusinessFunc', max_length=30, null=True)),
                ('ropaty', models.CharField(db_column='ROPATy', max_length=30)),
                ('dpo_name', models.CharField(db_column='DPO_Name', max_length=50)),
                ('businessunithead', models.CharField(blank=True, db_column='BusinessUnitHead', max_length=30, null=True)),
                ('logintime', models.DateTimeField(db_column='LoginTime')),
            ],
            options={
                'db_table': 'USER_DETAILS',
                'managed': False,
            },
        ),
    ]
